SELECT * FROM projetointegrador.tb_produto;
use projetointegrador;

-- Decoração / Papelão 1,1
insert into tb_produto values (DEFAULT,'Perfeita para despertar a criatividade nas brincadeiras infantis esse item fabricado 100% de papelão traz um ar mais descontraído para suas casa.',10, 'https://i.imgur.com/JOWy00P.jpg','Casa De Esqimó de Papelão', 189.00,'Largura: 120 cm Altura: 130 cm',null,1,1);
insert into tb_produto values (DEFAULT,'Essas simpáticas corujinhas fazem qualquer ambiente ter uma ar mais leve e podem ser fabricadas sem dificuldade por você.',10,'https://i.imgur.com/OM8o65d.jpg','Enfeites Corujas de Papelão', 57.00,'Largura: 25 cm Altura: 59 cm',null,1,1);
insert into tb_produto values (DEFAULT,'Sua sala Ficará muito mais elegante com um painel desses em uma de suas paredes, você terá um resultado excelente gastando muito pouco.',10, 'https://i.imgur.com/EfxiMmn.jpg','Painel de Parede Artístico vermelho', 125.00,'Largura: 220 cm Altura: 145 cm',null,1,1);
insert into tb_produto values (DEFAULT,'Sua sala Ficará muito mais elegante com um painel desses em uma de suas paredes, você terá um resultado excelente gastando muito pouco.',10, 'https://i.imgur.com/fwKjgLS.jpeg','Painel de Parede Artístico ', 125.00,'Largura: 220 cm Altura: 145 cm',null,1,1);
insert into tb_produto values (DEFAULT,'Uma casinha de passarinhos ficaria linda em seu jardim por exemplo, adquira já a sua.',10, 'https://i.imgur.com/eU9sEsp.jpg','Casa de Passarinho de Papelão', 48.00,'Largura: 27 cm Altura: 45 cm',null,1,1);
insert into tb_produto values (DEFAULT,'Uma excelente opção para quem quer fazer bonito gastando pouco e ainda contribuir para redução na produção de lixo.',10, 'https://i.imgur.com/aSOvFzV.jpg','Kit de papelão para Aniversário Infantil', 380.00,'Largura: 275 cm Altura: 205 cm',null,1,1);
insert into tb_produto values (DEFAULT,'Dê outra cara para o quarto de seu filho com esse kit de decoração',10, 'https://i.imgur.com/DmpeYYT.jpg','Kit de Decoração Quarto Infantil', 75.00,'Largura: 120 cm Altura: 95 cm',null,1,1);
insert into tb_produto values (DEFAULT,'Esse item é adequado para você que tem vários objetos de decoração e quer colocá-los em um lugar com mais visibilidade',10, 'https://i.imgur.com/nBbd5Oo.png','cachorro de papelão porta objetos', 78.00,'Largura: 80 cm Altura: 35 cm',null,1,1);

-- Decoração / madeira 1,2
insert into tb_produto values (DEFAULT,'Feito a mão com madeira reciclável de pallets e caixas de frutas, este brinquedo é perfeito para presentear do nono aos netos! Este brinquedo possui detalhes como: bancos internos, volante, alavanca de cambrio, retrovisores laterais, estepe e muito mais.', 10, 'https://i.imgur.com/TEw0QTC.jpg','Caminhão Basculante de Madeira', 188.00,'12.0 x 9.0 cm',null,1, 2);
insert into tb_produto values (DEFAULT,'Banco Soft 40 feito artesanalmente com madeira reciclável de pinus este produto é super ecológico e sustentável. Esta é uma peça coringa que não pode faltar na decoração da sua casa, seja no quarto, sala, cozinha ou varanda, ele simplesmente vai preencher aquele canto vazio e dar um toque todo especial.', 9, 'https://i.imgur.com/8tbFVSy.jpg','Banco Soft 40', 129.76,'40.0 x 26.0 cm',null,1, 2);
insert into tb_produto values (DEFAULT,'Caixa de correio artesanal feita em madeira reciclável de caixa de frutas e feira, super versátil pode ser instalada no portão ou diretamente no muro. Saia da mesmice e destaque a entrada de sua casa das demais.', 8, 'https://i.imgur.com/n9ylWk4.jpg','Caixa de correio artesanal', 188.00,'33.0 x 20.0 cm',null,1, 2);
insert into tb_produto values (DEFAULT,'Esta peça é super versatil e sustentável, pois é confeccionada com madeira mista reciclada. Ideal para simplificar seu dia a dia na cozinha, mas tambem pode ser uma ótima opção para presentear com originalidade.', 7, 'https://i.imgur.com/J4zu5hB.jpg','Suporte Para Papel Toalha Pratick', 145.28,'17.0 x 15.0 cm',null,1, 2);
insert into tb_produto values (DEFAULT,'Móvel Porta Toalhas Artez confeccionado com madeira de pinus reciclável, peça exclusiva e ecologicamente sustentável desde a sua concepção.Ideal para quartos, suites, clossets ou para decorar aquele cantinho vazio a espera de algo especial, este móvel vem para organizar e decorar o espaço.', 7, 'https://i.imgur.com/klD9HdY.jpg','Móvel Porta Toalhas Artez', 140.00,'90.0 x 70.0 cm',null,1, 2);
insert into tb_produto values (DEFAULT,'Porta talher de mesa Echo, confeccionado com madeira reciclada de caixotes de feira e copos de plastico de requeijão (isso mesmo copos de plastico de requeijão!!), peça exclusiva elaborada pela marcenaria boraceia para decorar a sua casa ou presentear de forma original.', 8, 'https://i.imgur.com/yY2ISzi.jpg','Porta Talher de Mesa Echo', 92.80,'25.0 x 9.5 cm',null,1, 2);
insert into tb_produto values (DEFAULT,'Porta Cartas e Correspondências, tamanho médio que comporta até revistas e pode ser instalado em paredes ou portas sob áreas cobertas como varandas, sacadas, consultórios, halls, condomínios etc. Ideal para quem já esta cansado de chegar em casa e ter que recolher aquele monte de correspondências, revistas e/ou jornais espalhados pelo chão, super facil de instalar!! Este é um produto exclusivo e ecológico, produzido com madeira reciclável extraída de caixas de fruta e feira, alem de ser confeccionado artesanalmente de forma sustentavel.', 9, 'https://i.imgur.com/uNOyeKy.jpg','Porta Cartas e Correspondências', 112.00,'32.0 x 15.0 cm',null,1, 2);
insert into tb_produto values (DEFAULT,'Porta revistas artesanal feito com madeira reciclável, esta peça é ideal para compor a decoração dos mais variados ambientes na sua casa ou escritório, alem de versátil este revisteiro é muito útil mantendo suas revistas e jornais sempre organizados. Bastante prático possui alça que facilita a remoção e limpeza. Este é um produto artesanal, confeccionado de maneira sustentável com madeira reciclada de pallets.', 9, 'https://i.imgur.com/S98Q6fF.jpg','Porta Revistas Artesanal em Madeira', 200.00,'43.0 x 16.0 cm',null,1, 2);

-- Decoração / pet 1,3
insert into tb_produto values (DEFAULT,'Peça feita artesanalmente feita com tampinha de Garrafa. O abajur foi feito apenas usando as tampinhas das garrafas pet e pode ser usado como destaque da sua sala de estar, do quarto ou de qualquer outro ambiente. Uma peça totalmente exclusiva e super moderna.', 10, 'https://i.imgur.com/ZqqRFQz.jpg','Luminária com tampinhas de garrafa', 99.99,'grande',null,1, 3);
insert into tb_produto values (DEFAULT,'Numa onda completamente sustentável, pense em enfeites que não usem só garrafas pet, mas também outro itens, como essas cápsulas famosas de café, que são descartados após o uso e que podem ganhar outra forma com um pouco de criatividade.', 10, 'https://i.imgur.com/vS3gytA.jpg','Guirlanda com garrafas pet, fitas e cápsulas de café.', 20.00,'pequeno',null,1, 3);
insert into tb_produto values (DEFAULT,'Esses aqui são super divertidos e ainda brincam com a nossa tendência a adotar elementos decorativos dos natais gelados do hemisfério norte. o algodão na garrafa dá a textura certa e a tampinha faz um gorro perfeito!', 10, 'https://i.imgur.com/3xIN4cy.jpg','Boneco de neve que não derrete no Natal brasileiro!', 6.99,'pequeno',null,1, 3);
insert into tb_produto values (DEFAULT,'Decore um cantinho especial da casa com um lindo jardim suspenso feito de garrafas PET.', 10, 'https://i.imgur.com/DDwEqeN.jpg','Jardim suspenso de garrafa PET', 30.00,'pequeno',null,1, 3);
insert into tb_produto values (DEFAULT,'Xícara de garrafa pet – Use como lembrancinha, decoração. Reciclagem de garrafa pet.', 10, 'https://i.imgur.com/sVWxW7L.jpg','xícara de garrafa pet', 5.00,'pequeno',null,1, 3);
insert into tb_produto values (DEFAULT,'Vasos feitos de garrafa para decorar mesa.', 10, 'https://i.imgur.com/TlOI1wZ.jpg','vaso de garrafa pet', 3.00,'pequeno',null,1, 3);
insert into tb_produto values (DEFAULT,'pinguins feitos com garrafas pet decoração de natal', 10, 'https://i.imgur.com/Mjp72M1.jpg','pinguins feitos com garrafas pet', 29.99,'pequeno',null,1, 3);
insert into tb_produto values (DEFAULT,'Natal sustentável: Papai noél feito de garrafa pet uma ótima decoração de natal para o seu jardim', 10, 'https://i.imgur.com/59cDgBR.jpg','Papai Noél feito de garrafa pet', 150.00,'grande',null,1, 3);

-- Decoração / pallet 1,4
insert into tb_produto values (DEFAULT,'Rack de Pallet envernizado para televisão', 10, 'https://i.imgur.com/Vdbr5U9.jpg','Rack de Pallet', 150.00,'grande',null,1, 4);
insert into tb_produto values (DEFAULT,'Estante para livros envernizado', 10, 'https://i.imgur.com/TYPZWxq.jpg','Estante para Livros', 120.00,'grande',null,1, 4);
insert into tb_produto values (DEFAULT,'Caixa de decoração para botijão de gás, feito de pallet', 10, 'https://i.imgur.com/ltQTWgF.jpg','Caixa para Botijão', 80.00,'grande',null,1, 4);
insert into tb_produto values (DEFAULT,'Pallet porta copos e xicaras. Decoração para cozinha alta durabilidade', 10, 'https://i.imgur.com/0L8V868.jpg','Porta Copos e xicaras', 150.00,'grande',null,1, 4);
insert into tb_produto values (DEFAULT,'Adega aberta para 8 garrafas, rustica e envernizada', 10, 'https://i.imgur.com/NoXY30g.jpg','Adega aberta para 8 garrafas', 120.00,'grande',null,1, 4);
insert into tb_produto values (DEFAULT,'Mesa decorativa para separação de espaços', 10, 'https://i.imgur.com/YRtCOz1.jpg','Copa divisora de espaço', 100.00,'grande',null,1, 4);
insert into tb_produto values (DEFAULT,'Estante suspensa por cordas, feita com pallets envernizados', 10, 'https://i.imgur.com/2thPMC8.jpg','Estante Suspensa', 170.00,'grande',null,1, 4);
insert into tb_produto values (DEFAULT,'Adega feita de pallet pintado, com porta. Material rustico e envernizado', 10, 'https://i.imgur.com/f3su37w.jpg','Adega de Pallet Fechada', 170.00,'grande',null,1, 4);


-- artigos/ Papelão
insert into tb_produto values (DEFAULT,'Moldura para quadros em papelão, detalhada em cores vivas', 20, 'https://i.imgur.com/zfPZ4qF.jpg','Moldura para quadros em papelão', 39.99,'20cm x 10cm',null,2, 1);
insert into tb_produto values (DEFAULT,'Casinnha para Gatos em forma de cacto, toda moldada em papelão, em formato ilustrativo de um cacto', 20, 'https://i.imgur.com/CsZFhMA.jpg','Casa para gato em forma de Cacto', 149.99,'Grande',null,2, 1);
insert into tb_produto values (DEFAULT,'Porta canetas decorado em papelão, com espaços iguais para organização de objetos de estudo', 20, 'https://i.imgur.com/5dvvpMk.jpg','Porta canetas', 79.99,'40cm x 30cm',null,2, 1);
insert into tb_produto values (DEFAULT,'Vaso para planta, decorado com formas de arte em papelão', 20, 'https://i.imgur.com/cODCwT8.jpg','Vaso para plantas', 99.99,'60cm x 60cm',null,2, 1);
insert into tb_produto values (DEFAULT,'Casinha para PET toda construída em papelão, decorada', 20, 'https://i.imgur.com/2CfUPIB.jpg','Casinha para PET', 129.99,'Grande',null,2, 1);
insert into tb_produto values (DEFAULT,'Quadro em caixa de pizza, ilustrado em artes desenhada pelo pintor Alexander Pilattes', 20, 'https://i.imgur.com/AE8AnZL.jpg','Quadro em caixa de pizza', 39.99,'médio',null,2, 1);
insert into tb_produto values (DEFAULT,'Casa para passarinho decorada com flores pintada em azul, roxo e amarelo', 20, 'https://i.imgur.com/EnsQQPX.jpg','Casinha para passarinho', 139.99,'grande',null,2, 1);
insert into tb_produto values (DEFAULT,'Decoração de natal para enfeite em mesa', 20, 'https://i.imgur.com/vwO4Xq1.jpg','Decoração arvoré de natal', 19.99,'15cm x 9cm',null,2, 1);


-- artigos/ madeira
insert into tb_produto values (DEFAULT,'Boneca de madeira da Frida Kahlo para podeixar decorar sua casa ou até mesmo dar de presente.',20, 'https://i.imgur.com/48YNbPr.jpg','Frida Boneca de Madeira', 63.10,'Altura: 12 cm',null,2,2);
insert into tb_produto values (DEFAULT,'Pássaro feito de madeira com bico diferenciado com alta qualidade e capricho.',30, 'https://i.imgur.com/WMuS67f.jpg','Pássaro em madeira', 65.00,'Largura: 3.30 cm Altura: 13.50 cm',null,2,2);
insert into tb_produto values (DEFAULT,'Plaquinha em cerâmica plástica com código spotify esculpido com o intuito de ser moderninha e artesanal.',70, 'https://i.imgur.com/lwtZu4a.jpg','Pulseira Spotify personalizada', 35.00,'Largura: 1 cm Comprimento: 4 cm',null,2,2);
insert into tb_produto values (DEFAULT,'Anel de madeira reciclada, com pequenos detalhes perfeitos e madeira tratada para não penetrar água.',50, 'https://i.imgur.com/CTLkWoe.jpg','Anel de madeira', 31.69,'Numeração 17',null,2,2);
insert into tb_produto values (DEFAULT,'Abridor de garrafa fabricado em Madeira maciça personalizado com logo ou brasão.',100, 'https://i.imgur.com/9lN9dvW.jpg','Abridor de garrafa em madeira', 25.00,'Largura: 3.50 cm Altura: 2 cm',null,2,2);
insert into tb_produto values (DEFAULT,'O Calendário Brinquedos é produzido em madeira, contendo a caixa e números na cor preta, seu formato é no estilo dados, seu modelo é montável, é utilizado para decoração de ambientes como escritórios, quarto de estudos, salas.',25, 'https://i.imgur.com/klSwgnc.jpg','Calendário de Madeira', 88.00,'Largura: 6.40 cm Altura: 8.50 cm',null,2,2);
insert into tb_produto values (DEFAULT,'Nuvem para decoração quarto de bebe e porta de maternidade, fabricado e entregue na cor da madeira pinus com fundo em MDF pintado.',15, 'https://i.imgur.com/uZJoMGn.jpg','Nuvem de madeira com plaquinha', 73.90,'Comprimento: 30 cm Altura: 21 cm',null,2,2);
insert into tb_produto values (DEFAULT,'Kit montanhas recortado em pinus, possuindo 2 montanhs grandes, 3 médias e 1 pequena',37, 'https://i.imgur.com/rsXjkhm.jpg','Kit montanhas de madeira', 37.80,'Largura: 10 cm Altura: 20 cm',null,2,2);


-- artigos/ pet

insert into tb_produto values(DEFAULT,'Casa de passarinhos feitos de carrafa pet decorada',10,'https://i.imgur.com/bSS3lZ6.jpg','Casa de Passarinhos','29.99','25mc x 20cm',null, 2, 3);
insert into tb_produto values(DEFAULT,'Luminaria feita de garrafa pet, ideial para sala de jantar, sala de visitas e corredores',10,'https://i.imgur.com/KriBj6Z.jpg','Luminaria Rústica','39.99','50cm x 30mc',null, 2, 3);
insert into tb_produto values(DEFAULT,'Suporte de organização, ideal para escritórios e bancadas de estudos',10,'https://i.imgur.com/UfgxQXM.jpg','Kit Organizador','69.99','30 cm x 15cm',null, 2, 3);
insert into tb_produto values(DEFAULT,'Lustres feitos de garrafa pet ideial para sala de jantar e cozinha',10,'https://i.imgur.com/uQd7N20.jpg','Lustre Pet','119.99','60cm x 30cm',null, 2, 3);
insert into tb_produto values(DEFAULT,'Kit armazenador de temperos, ideal para deixar seus temperos organizados na sua cozinha',10,'https://i.imgur.com/OM8mi8z.jpg','Kit Temperos','49.99','pequeno',null, 2 ,3);
insert into tb_produto values(DEFAULT,'Vaso de garrafa pet ilusionista, chique e sofisticado para colocar em mesas de jantar e mesas de centro',10,'https://i.imgur.com/Z3lFGV2.jpg','Vaso Ilusionista','79.99','pequeno',null, 2, 3);
insert into tb_produto values(DEFAULT,'Vaso de Flores de garrafa pet fino e sofisticado, ideal para mesas',10,'https://i.imgur.com/sQ7I6xo.jpg','Vaso de Flores','49.99','médio',null, 2 ,3);
insert into tb_produto values(DEFAULT,'Vaso de Mini plantas, ideal para colocar em mesas e paineis de jardim horizontal',10,'https://i.imgur.com/uqgIyKS.jpg','Vaso Mini plantas','19.99','pequeno',null, 2 ,3);

-- artigos/ pallet
insert into tb_produto values (DEFAULT,'Porta Papéis feito de pallet especialmente para colocar no banheiro',10,'https://i.imgur.com/C59kXJ5.jpg','Porta Papéis de pallet com suporte de corda',119.99,'1m x 60 cm',null, 2, 4);
insert into tb_produto values(DEFAULT,'Suporte para colocar enfeites e plantas em lugares com pouco espaço',10,'https://i.imgur.com/BqMwpZN.jpg','Suporte para Enfeites de pallet',149.99,'1m x 50 cm','null', 2, 4);
insert into tb_produto values(DEFAULT,'Porta Toalhas de rosto para banheiro feito de pallet e cores rústicas',10,'https://i.imgur.com/1VDoLLu.jpg','Suporte de Toalhas e Itens de Higienie',130.00,'45cm x 90 cm',null, 2, 4);
insert into tb_produto values(DEFAULT,'Painel para Jardim Vertical feito de pallet e cor rústica levando mais tons de natureza','10','https://i.imgur.com/2fjbLbc.jpg','Painel Jardim Vertical',59.90,'2m x 1m',null, 2, 4);
insert into tb_produto values(DEFAULT,'Porta Chaves produzido com pallet e cor de madeira maciça',10,'https://i.imgur.com/Wm9FuuO.jpg','Porta Chaves Nature',49.99,'80cm x 30cm',null, 2, 4);
insert into tb_produto values(DEFAULT,'Adega feita com pallet especialmente para sala de jantar e salas de visitas',10,'https://i.imgur.com/jNJ9WO7.jpg','Adega Palleteira',800.0,'2m x 1m',null, 2, 4);
insert into tb_produto values(DEFAULT,'Tremzinho para jardins feito de pallet branco para dar destaque no seu jardim',10,'https://i.imgur.com/Pg2rPva.jpg','Tremzinho de Jardim',300.00,'30 cm x 2m',null, 2 , 4);
insert into tb_produto values(DEFAULT,'Painel para enfeites e plantas com suporte de cordas rústicas',10,'https://i.imgur.com/dIsR8ih.jpg','Painel para Enfeites e Plantas',250.00,'2m x 1m', 2, 4);

-- utensilios/ Papelão
insert into tb_produto values (DEFAULT,'Lustre decorativo suspenso feito em papelão, com suporte e fiação para luz', 20, 'https://i.imgur.com/ROhgB9W.jpg','Lustre decorativo', 179.99,'60cm x 30cm',null,3, 1);
insert into tb_produto values (DEFAULT,'Lanterna decorativa móvel revestida em paleção e com fiaçõa incuída', 20, 'https://i.imgur.com/wOaWqfH.jpg','Lanterna decorativa', 69.99,'30cm x 40cm',null,3, 1);
insert into tb_produto values (DEFAULT,'Arandela com viés com tiras em papelão, ideal para iluminar espaços neutros', 20, 'https://i.imgur.com/Th29gI5.jpg','Arandela com viés', 240.99,'60cm x 50cm',null,3, 1);
insert into tb_produto values (DEFAULT,'Nichos para organização em formato de coração moldado todo em papelão', 20, 'https://i.imgur.com/2rUuTVp.jpg','Nichos em papelão', 200.00,'Grande',null,3, 1);
insert into tb_produto values (DEFAULT,'Lustre suspenso feito com papelão, com tubulares para lâmpadas', 20, 'https://i.imgur.com/ffvychQ.jpg','Lustre suspenso tubular', 399.99,'Grande',null,3, 1);
insert into tb_produto values (DEFAULT,'Maletas porta coisas, todo feito em papelão, com alça ', 20, 'https://i.imgur.com/kKY6aCO.jpg','Maletas coloridas em papelão', 39.99,'Médio',null,3, 1);
insert into tb_produto values (DEFAULT,'Cofrinhos de papelão em cores, ótimo para guardar economias', 20, 'https://i.imgur.com/Nsc4Qnq.jpg','Cofrinho de papelão', 9.99,'Pequeno',null,3, 1);


-- utensilios/ madeira
insert into tb_produto values (DEFAULT,'Paneleiro Rústico Em Ferro E Madeira Tratada possuindo 6 ganchos removíveis acomoda 5 pratos, seis copos e talhares.',30, 'https://i.imgur.com/93CKmGp.jpg','Paneleiro Rústico Em Ferro E Madeira', 139.09,'Largura: 30 cm Altura: 37 cm',null,3,2);
insert into tb_produto values (DEFAULT,'Porta tempero de madeira com capacidade de 12 potes de vidro, e as prateleira são removíveis para maior conforto.',13, 'https://i.imgur.com/dln5q2D.jpg','Porta tempero de madeira',139.90,'Comprimento: 33 cm Altura: 44 cm',null,3,2);
insert into tb_produto values (DEFAULT,'Plaquinha em cerâmica plástica com código spotify esculpido com o intuito de ser moderninha e artesanal.',70, 'https://i.imgur.com/lwtZu4a.jpg','Pulseira Spotify personalizada', 35.00,'Largura: 1 cm Comprimento: 4 cm',null,3,2);
insert into tb_produto values (DEFAULT,'Suporte de madeira de pallet envernizado em mogno com capacidade de 3 rolos.',90, 'https://i.imgur.com/XLYa7Ih.jpg','Suporte de Madeira Para Banheiro', 55.00,'Largura: 17 cm Altura: 40 cm',null,3,2);
insert into tb_produto values (DEFAULT,'Suporte feito de madeira de pinus, cores e textura da madeira pode sofrer variações e com 2 degraus para suporte de plantas',40, 'https://i.imgur.com/rgtBM0G.jpg','Suporte para plantas', 265.00,'Largura: 45 cm Altura: 55 cm',null,3,2);
insert into tb_produto values (DEFAULT,'Estante de madeira de pinus e aço, cor e textura da madeira pode sofrer variações',25, 'https://i.imgur.com/3n6aGUl.jpg','Estante de madeira de pinus', 225.00,'Largura: 30 cm Altura: 80 cm',null,3,2);
insert into tb_produto values (DEFAULT,'Nicho Rústico de Madeira, a madeira é o suprassumo do decor, e combina com qualquer outro material e tonalidade.',15, 'https://i.imgur.com/SAkSBXC.jpg','Nicho Rustico de Madeira', 71.00,'Largura: 12 cm Altura: 18 cm',null,3,2);
insert into tb_produto values (DEFAULT,'Caneca em madeira de reflorestamento, para líquidos frios (cerveja, vinho,suco,água, etc.) estilo rústico,impermeabilizada com resina e com capacidade para 420.ml.',100, 'https://i.imgur.com/eopMPBy.jpg','Caneca em madeira', 74.20,'Altura: 11 cm',null,3,2);



-- utensilios/ pet  4,3
insert into tb_produto values (DEFAULT,'Vaso decorado para ambientes internos fsbricado com garrafa pet.',10, 'https://i.imgur.com/N8qEr4u.jpg','Vaso Decorado',12.00,'Largura: 25 cm Altura: 29 cm',null,4,3);
insert into tb_produto values (DEFAULT,'prateleiras para usos diversos com estrutura baseada em material reciclavel.',10, 'https://i.imgur.com/ffVoVn4.jpg','Prateleira Sustentável', 57.00,'Largura: 75 cm Altura: 28 cm',null,4,3);
insert into tb_produto values (DEFAULT,'Cortina decorativa para ambientes internos fabricada em plastico.',10, 'https://i.imgur.com/zgjEsSW.jpg','Cortina Decorativa', 96.00,'Largura: 75 cm Altura: 229 cm',null,4,3);
insert into tb_produto values (DEFAULT,'Ninho para passarinhos ideal para atraí-los para o seu jardim.',10, 'https://i.imgur.com/tAd8coX.jpg','Ninho de passarinho', 38.00,'Largura: 22 cm Altura: 27 cm',null,4,3);
insert into tb_produto values (DEFAULT,'Porta Objetos de parede indicado para ambientes internos para facilitar a organização do ambiente.',10, 'https://i.imgur.com/egbn0Xy.jpg','Porta Objetos de Parede', 17.00,'Largura: 18 cm Altura: 22 cm',null,4,3);
insert into tb_produto values (DEFAULT,'Porta Objetos de mesa indicado para facilitar a organização do ambiente de estudos.',10, 'https://i.imgur.com/89TEshu.jpg','Porta Objetos de Mesa', 23.00,'Largura: 25 cm Altura: 29 cm',null,4,3);
insert into tb_produto values (DEFAULT,'Puxa-sacos simples e de facil produção indicado para você que preza pela praticidade.',10, 'https://i.imgur.com/besCtZA.jpg','Puxa-Sacos', 17.00,'Largura: 25 cm Altura: 38 cm',null,4,3);
insert into tb_produto values (DEFAULT,'Porta mantimentos de baixo custo e grande durabilidade fabricado em garrafa pet.',10, 'https://i.imgur.com/OnCeAL9.jpg','Porta mantimentos', 8.00,'Largura: 25 cm Altura: 29 cm',null,4,3);

-- utensilios/ pallet
insert into tb_produto values (DEFAULT,'Nossos produtos são todos ecologicamente corretos pois utilizamos a política dos 3R - Reduzir, Reutilizar e Reciclar, com isso trazemos para os nossos clientes uma consciência ecológica e de preservação do meio ambiente.', 8, 'https://i.imgur.com/N4tn8jw.jpg','Armario de pallets',1200.00 ,'120.0 x 50.0 cm ',null,3,3 );
insert into tb_produto values (DEFAULT,'Nossos produtos são todos ecologicamente corretos pois utilizamos a política dos 3R - Reduzir, Reutilizar e Reciclar, com isso trazemos para os nossos clientes uma consciência ecológica e de preservação do meio ambiente.', 10, 'https://i.imgur.com/EzJifHX.jpg','Baú de Pallets Grande', 432.00,'70.0 x 52.0 cm ',null,3,3 );
insert into tb_produto values (DEFAULT,'Nossos produtos são todos ecologicamente corretos pois utilizamos a política dos 3R - Reduzir, Reutilizar e Reciclar, com isso trazemos para os nossos clientes uma consciência ecológica e de preservação do meio ambiente.', 9, 'https://i.imgur.com/N4tn8jw.jpg','Poltrona de Pallets', 270.00,'70.0 x 52.0 cm',null,3,3 );
insert into tb_produto values (DEFAULT,'Linda base de sofá feita com pallets reciclados de único uso, são totalmente desmontados e lixados um a um, para melhor conservação do produto. Nossos produtos são todos ecologicamente corretos pois utilizamos a política dos 3R - Reduzir, Reutilizar e Reciclar, com isso trazemos para os nossos clientes uma consciência ecológica e de preservação do meio ambiente.', 6, 'https://i.imgur.com/XMcmmlO.jpg','Base de Sofá em pallets',486.00,'30.0 x 80.0 cm ',null,3,3 );
insert into tb_produto values (DEFAULT,'Linda Cama de Casal feita com pallets reciclados de único uso, são totalmente desmontados e lixados um a um, para melhor conservação do produto. Nossos produtos são todos ecologicamente corretos pois utilizamos a política dos 3R - Reduzir, Reutilizar e Reciclar, com isso trazemos para os nossos clientes uma consciência ecológica e de preservação do meio ambiente.', 8, 'https://i.imgur.com/M8eHuoz.jpg','Cama de Casal de pallets com gavetas', 594.00,'45.0 x 160.0 cm ',null,3,3);
insert into tb_produto values (DEFAULT,'Cômoda de Pallets Personalizada.Estrutura em Pallets Reciclados, com 4 portas e 3 prateleiras ao centro. Acabamentos:Natural, Mogno, Imbuia, Nogueira, Cores Foscas.', 8, 'https://i.imgur.com/6afJHL5.jpg','Comoda de Pallets Personalizada', 1188.00,'70.0 x 60.0 cm ',null,3,3 );
insert into tb_produto values (DEFAULT,'Home Office de Pallets. Estrutura em Pallets Reciclados, com 2 suportes para teclados com corrediças telescópicas, 2 armários e 2 gavetões no centro. Acabamentos:Natural, Mogno, Imbuia, Nogueira, Cores Foscas.', 7, 'https://i.imgur.com/OD2yYCD.jpg','Home Office de Pallets', 1350.00 ,'0.75 x 0.60 cm ',null,3,3);
insert into tb_produto values (DEFAULT,'Linda base de sofá feita com pallets reciclados de único uso, são totalmente desmontados e lixados um a um, para melhor conservação do produto. Nossos produtos são todos ecologicamente corretos pois utilizamos a política dos 3R - Reduzir, Reutilizar e Reciclar, com isso trazemos para os nossos clientes uma consciência ecológica e de preservação do meio ambiente.', 7, 'https://i.imgur.com/mN1Q6fL.jpg','Jogo de sofa de pallets e mesa de centro', 1080.00 ,'40.0 x 80.0 cm ',null,3,3 );

-- moveis/ Papelão 4,1
insert into tb_produto values (DEFAULT,'Poltrona de Papelão grande, feita com papelão reforçado', 20, 'https://i.imgur.com/ICFYe1c.jpg','Poltrona Adulto de Papelão', 150.00,'Largura: 90 cm Altura: 79 cm',null,4,1);
insert into tb_produto values (DEFAULT,'Estante para livros com 8 prateleiras', 20, 'https://i.imgur.com/pvdRuf4.jpg','Estante para livros', 200.00,'Largura: 90 cm Altura: 1,50 cm',null,4,1);
insert into tb_produto values (DEFAULT,'Sapateira com 8 slots para sapatos. Cabe 8 pares de sapatos.', 20, 'https://i.imgur.com/6vfEiXr.jpg','Sapateira de Papelão ', 90.00,'Largura: 90 cm Altura: 1,50 cm',null,4,1);
insert into tb_produto values (DEFAULT,'Sapateira com 3 prateleiras, cabem 12 pares de sapatos.', 20, 'https://i.imgur.com/RAh0gLN.jpg','Sapateira de Papelão 10 slots ', 120.00,'Largura: 90 cm Altura: 1,50 cm',null,4,1);
insert into tb_produto values (DEFAULT,'Poltrona Rustica com apoios para braço.', 20, 'https://i.imgur.com/f6l0Kft.jpg.jpg','Poltrona Rustica', 300.00,'Largura: 90 cm Altura: 1,50 cm',null,4,1);
insert into tb_produto values (DEFAULT,'Caixa para armazenar roupas sujas para lavar.', 20, 'https://i.imgur.com/avSaz4r.jpg','Caixa de Roupas pra Lavar', 70.00,'Largura: 90 cm Altura: 1,50 cm',null,4,1);
insert into tb_produto values (DEFAULT,'Mesa de Cantoneira: Serve para colocar objetos e decorações.', 20, 'https://i.imgur.com/hsWXmi1.jpg','Mesa de Canto', 80.00,'Largura: 90 cm Altura: 1,50 cm',null,4,1);
insert into tb_produto values (DEFAULT,'Guarda-Roupa pequeno, com prateleiras, gavetas e cabideiro feito de papelão.', 20, 'https://i.imgur.com/zgMO9rE.jpg','Guarda-Roupas Pequeno', 120.00,'Largura: 90 cm Altura: 1,50 cm',null,4,1);


-- moveis/ madeira 4,2
insert into tb_produto values (DEFAULT,'Mesa em Madeira de Eucalipto com cantos arredondados para áreas internas poid não tem tratamento com Impregnante Stain.', 20, 'https://i.imgur.com/fOUaQYi.jpg','Mesa Sala de Jantar em Madeira Angra', 1500.00,'Profundidade: 160 cm Largura: 90 cm Altura: 79 cm',null,4,2);
insert into tb_produto values (DEFAULT,'O estilo de mesa perfeito para um diretor! Uma mesa em L para escritório proporciona mais comodidade no momento de sua utilização. Conta com 02 gavetas que auxiliam na organização de seu espaço, e junto com seu design traz mais modernidade ao ambiente. Garanta já a sua!', 20, 'https://i.imgur.com/ZboUGZ2.jpg','Mesa Para Escritório Home Office em L de madeira', 710.00,'180 x 75 x 70 cm',null,4,2);
insert into tb_produto values (DEFAULT,'Este banco foi elaborado em madeira de demolição com tratamento anti-cupins, ou seja, retirada de casarões e fazendas demolidas e transformado num artigo exclusivo! ', 20, 'https://i.imgur.com/93n6IDs.jpg','Banco Mineiro Tuna Em Madeira De Demolição', 517.00,'Dimensões: Comprimento = 1,80m Altura = 0,45m',null,4,2);
insert into tb_produto values (DEFAULT,'A Cama Tarumã é um modelo baixo e possui um designe oriental. Ela permite muitas possibilidades, você pode escolher diferentes tipos de colchões para compor sua cama (Casal ou Queen), devido a estrutura privilegiada desse móvel. Também é indicada para quem tem dificuldade de mobilidade e/ou não se adapta a camas muito altas. Pintura ultra violeta com impressão amadeirada.', 20, 'https://i.imgur.com/ksJiUcU.jpg','Cama Casal/Queen Tarumã MadeiraMadeira Carvalho ', 599.99,'160 X 200 CM',null,4,2);
insert into tb_produto values (DEFAULT,'Banco de Jardim Rústico de Madeira 2 Lugares com Encosto Móveis Meneghetti Envelhecido', 20, 'https://i.imgur.com/sTDTYyB.jpg','Bamco de madeira para jardim', 299.99,'Grande',null,4,2);
insert into tb_produto values (DEFAULT,'Painel para TV FEITO EM MADEIRA REFLORESTADA DE PINUS.', 20, 'https://i.imgur.com/ZboUGZ2.jpg','Painel Para Tv De Madeira Demolição', 299.99,'1.20 X 1.00 CM',null,4,2);
insert into tb_produto values (DEFAULT,'estante de madeira para televisão. Os espaços vazados podem ser usados como compartimentos para outros acessórios e aparelhos eletrônicos que acompanham a tv.', 20, 'https://i.imgur.com/HGmJ1Ng.jpg','Estante de Madeira', 499.99,'grande',null,4,2);
insert into tb_produto values (DEFAULT,'Ideal para sua sala de jantar, toda em madeira maciça os "rios" de resina passam por toda sua superfície preenchendo todas as rachaduras, ressaltando ainda mais a beleza da madeira que fica com aspecto vidrificado.', 20, 'https://i.imgur.com/YWGdR2T.jpg','Mesa de Madeira Reciclavel', 999.99,'grande',null,4,2);

-- moveis/ pet 4,3
insert into tb_produto values (DEFAULT,'Banco com assento e encostos fabricados em garrafa Pet que fica bem em ambientes externos e de lazer..',10, 'https://i.imgur.com/BrUoigo.jpg','Banco de Pets', 138.00,'Largura: 120 cm Altura: 55 cm',null,4,3);
insert into tb_produto values (DEFAULT,'Lixeira fabricada 100% com tanpinhas de Garrafas Pet que pode ser usada inclusive para separar os diferentes tipos de lixo.',10, 'https://i.imgur.com/V8pTANb.jpg','Lixeira de Tampinhas', 47.00,'Largura: 45 cm Altura: 75 cm',null,4,3);
insert into tb_produto values (DEFAULT,'Cadeira Fabricada com assento e encosto em tampinhas de pets muito confortável e ecologicamente correta.',10, 'https://i.imgur.com/PhqoO37.jpg','Cadeira de Tampinhas', 88.00,'Largura: 50 cm Altura: 75 cm',null,4,3);
insert into tb_produto values (DEFAULT,'Sofá e Puff Com estruturas em garrafas pets economize ao mesmo tempo que contribui com o meio ambiente sem perder o conforto. ',10, 'https://i.imgur.com/3Cl73KE.jpg','Sofá e Puff', 135.00,'Largura: 140 cm Altura: 85 cm',null,4,3);
insert into tb_produto values (DEFAULT,'Vasos para plantas confeccionados em pet pode ser colocado em diversos tipos de ambiente',10, 'https://i.imgur.com/V0VAukI.jpg','Vaso em Pet', 7.00,'Largura: 25 cm Altura: 29 cm',null,4,3);
insert into tb_produto values (DEFAULT,'Puffs estruturado em garrafas pets, perfeito para incluir um item com matéria prima reciclada e ecologicamento correto em sua casa.',10, 'https://i.imgur.com/9OVpx95.jpg','Puffs Sustentáveis', 33.00,'Largura: 55 cm Altura: 55 cm',null,4,3);
insert into tb_produto values (DEFAULT,'Essa casa fabricada com garrafas pet em sua estrutura fará toda diferença nas brincadeiras das crianças e já introduz nelas a ideia de sustentabilidade',10, 'https://i.imgur.com/ztK7pvk.jpg','Casinha Infantil', 115.00,'Largura: 125 cm Altura: 35 cm',null,4,3);
insert into tb_produto values (DEFAULT,'Estante para sala de estar estruturada 100% em material reciclado excelente para trazer um ar de consumo sustentável para o seu lar.',10, 'https://i.imgur.com/JvNfNJp.png','Estante Reciclável', 255.00,'Largura: 120 cm Altura: 65 cm',null,4,3);


-- moveis/ pallet
insert into tb_produto values (DEFAULT,'Peça feita artesanalmente feita de Pallet. Cama de casal Padrão feita de Pallets com tratamento anti cupim! Super resistente !! Madeira sustentável!', 899.99, 'https://i.imgur.com/cizNLZN.jpg','Cama feita de Pallets', 1200.00,'1,60 X 2,40 cm',null,4, 4);
insert into tb_produto values (DEFAULT,'Peça feita artesanalmente com pallets.  Assento feito de pallets madeira reflorestada (Pínus), produzido com madeira seca e aparelhada. o banco de pallet duplo acomoda duas pessoas e no centro é possível observar a presença de uma mesa de madeira embutida na sua estrutura. Esse móvel além de servir como assento pode ser utilizado como apoio de objetos decorativos.', 999.99, 'https://i.imgur.com/uAo5AK3.jpg','Banco feito de Pallets', 189.99,'0,80 x 0,60 cm',null,2, 4);
insert into tb_produto values (DEFAULT,'Peça feita artesanalmente com ripas de pallet reaproveitados para colocação de vasinhos de planta.', 399.99, 'https://i.imgur.com/YVdJqvx.jpg','Painel Pallet decorativo', 139.99,'1,20 x 1,00 cm',null,1, 4);
insert into tb_produto values (DEFAULT,'A cama feita de palete também é perfeita para ambientes decorados com o estilo boho. Isso porque, a simplicidade da madeira completa a decoração casual do boho, que integra características de diferentes épocas e culturas, como as estampas e o ar místico do estilo hippie e as cores neutras do ambiente vintage.', 20, 'https://i.imgur.com/5Wp6I47.jpg','Cama no estilo boho', 1999.99,'1,60 X 2,40 cm',null,4,4);
insert into tb_produto values (DEFAULT,'Peça feita artesanalmente com Pallet reciclavel. Mesa rústica feita toda de paletes para quem gosta de criatividade', 20, 'https://i.imgur.com/vw1U33Y.jpg', 1299.00,'Grande',null,4,4);
insert into tb_produto values (DEFAULT,'Escrivaninha (mesa de computador, mesa de escritório) de pallet', 20, 'https://i.imgur.com/8im0rv1.jpg','Escrivaninha de Pallet', 699.99,'0,70 x 1,50 cm',null,2,4);
insert into tb_produto values (DEFAULT,'Rack feito com pallets, ideal para organizar seu ambiente', 20, 'https://i.imgur.com/bEHTj8L.jpg','Rack em pallet', 399.99,'0,70 x 1,50 cm',null,2,4);


